version: '3'
services:
  db:
    env_file: .env
    environment:
      - MYSQL_DATABASE=test_db
    build:
      context: ./MySQL
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    env_file: .env
    build:
      context: .
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
  web:
    build:
      context: ./web
    container_name: nginx_web
    ports:
        - "80:80"
